### ISSUE TITLE
Support for non msbuild projects

### ISSUE THREAD

**Issue by baywet** [rencoreab/sharepoint-sonarqube#2]
Hi,
It's currently not clear given the current documentation if only MSBuild projects are required and/or if we need to install anything on top of Visual Studio (the IDE).
After a few attempts I suspect it's not currently possible, without MSBuild projects and an extension installed on the VS that does the build part.
Adding support for non MSBuild projects would be a great addition to this sonarqube plugin.
Our scenario: we do client side development only and push our webpart definitions via pnp provisioning (similar to the spfx in certain ways).
Adding support for non MSBuild project would allow analysis of:
- Custom PowerShell scripts, part of a project or not
- Custom JavaScript/TypeScript, part of a project or not (including things like checking if cache is implemented for sp-pnp-js usage)
- Pnp Provisioning templates
- Spfx "projects"

**Comment by HughWood** [comment]
Hi @baywet ,

If you own a license for the correct version of SPCAF you can use a gulp task for analysis instead of TFS. Visual Studio isn't involved here as this is part of an automated ALM toolchain.

https://docs.spcaf.com/v6/SPCAF_OVERVIEW_680_HOWTORUNSPCAFSPFXGULP.html

You will need to use a sonarqube runner gulp task to execute the analysis and setup the drop locations accordingly.

This is a process we aren't supporting officially, however presuming you have the correct licensing please feel free to contact https://support.rencore.com to gain direct support in setting this up.

Kind regards,
Hugh Wood
Lead Developer
Rencore

**Comment by baywet** [comment]
Hi Hugh,
Thanks for the fast reply.
In our case we're not using gulp but webpack.
The static analysis is run by the sonarqube CLI analysis task in VSTS. (CLI runner)
What would be the steps there besides adding the plugins to SQ, configuring the profiles and adding the license?

**Comment by HughWood** [comment]
Hi @baywet ,

This is something that hasn't been executed by us, but I would presume you have a task that execute sonarqube, however we don't have a webpack task for spcaf and the runner isn't built to support this requiring a quality gate license to execute as a command line application using the child process api, providing the drop location and then executing the sonarqube task from webpack.

Kind regards,
Hugh Wood
Lead Developer
Rencore GmbH

**Comment by baywet** [comment]
Thanks @HughWood I think we can leave webpack out of the picture here. We're using the CLI runner to run the static analysis for Sonarqube. This runs analysis for all the plugins within the same process.
So the question is: if I run the static analysis from CLI runner, on a non-msbuild project, is the rencore plugin supposed to run analysis?

**Comment by HughWood** [comment]
@baywet all you require is for the report to be in the correct drop location from the SPCAF runner depending on which one you use. If it's there when the sonarqube-runner executes it will be picked up.

The configuration stays the same apart from the source of task.

Further the sonarqube plugin is open source, so you can of course modify this if you require anything slightly different to get it to run in a special case scenario.

Kind regards,
Hugh Wood
Lead Developer
Rencore GmbH

**Comment by baywet** [comment]
So the flow would be:
Custom vsts build spcaf task to generate a report
Sonarqube vsts cli task to pick up that report

(given I have a license and the plugins installed on the server)
Correct?

**Comment by HughWood** [comment]
@baywet,
That would be correct yes

Kind regards,
Hugh Wood
Lead Developer
Rencore GmbH

**Comment by baywet** [comment]
The download link only provides the task and not a complete extension.
It's apparently not possible to add build tasks like that in VSTS (the hosted by Microsoft version of TFS), you have to leverage an extension either via the marketplace or private extensions share.
https://www.visualstudio.com/en-us/docs/integrate/extensions/publish/overview#upload 
The SPCAF extension doesn't show up on the marketplace, also I'm assuming it doesn't exist or it's private.
Do you have a private extension on the marketplace? if yes would it be possible to share it with us so we can try it out?

**Comment by HughWood** [comment]
Hi @baywet 

We have a detailed explanation of how this works here:

https://docs.spcaf.com/v6/SPCAF_OVERVIEW_665_HOWTORUNSPCAFINTFS2015.html

Kind regards,
Hugh Wood
Lead Developer
Rencore GmbH

**Comment by baywet** [comment]
Hi @HughWood ,
Thanks for pointing out the doc and sorry for the delay in the answer.
What permissions are needed to execute that? (the upload task), I'm Project Collection Administrator of our VSTS account and I get a 401 Unauthorized.

**Comment by russelldyas** [comment]
Hello @baywet 

Hugh asked me to reply to your above query. I am sorry that you were unable to continue uploading the task. The access level should be fine.

Can I confirm you are using Alternate authentication credentials?  If not you can create a set of crenditials by following the steps below

1. Sign into VSTS.
2. Click on your username on the VSTS page and click on My profile.
3. From there, click on the Security tab and you will see the Alternate authentication credentials section
4. Tick Enable alternate authentication credentials and enter a set of new credentials
5. Click save

Once you have created the credentials you should be able to use them in the upload program.  

I am sorry we have recently updated the How To article with this information but it has not yet been published live.

Please let me know if you are still having problems uploading.

From

Russell

**Comment by baywet** [comment]
Thanks for the help @russelldyas that worked. It probably should be part of the documentation.
Any way to have the license not on source control and not as a static file on the build machine? (more like a build variable or a service connection)

**Comment by baywet** [comment]
Also now that I got the VSTS part almost figured out and the reports generated. Once I install the plugins in SonarQube I get this error message during the SQ cli task:
```
ERROR: Error during SonarQube Scanner execution
java.lang.IllegalStateException: Unable to load component class org.sonar.scanner.report.MetadataPublisher
at org.sonar.core.platform.ComponentContainer$ExtendedDefaultPicoContainer.getComponent(ComponentContainer.java:69)
at org.picocontainer.DefaultPicoContainer.getComponent(DefaultPicoContainer.java:621)
at org.picocontainer.parameters.CollectionComponentParameter.getArrayInstance(CollectionComponentParameter.java:334)
at org.picocontainer.parameters.CollectionComponentParameter.access$100(CollectionComponentParameter.java:49)
at org.picocontainer.parameters.CollectionComponentParameter$1.resolveInstance(CollectionComponentParameter.java:139)
at org.picocontainer.parameters.ComponentParameter$1.resolveInstance(ComponentParameter.java:141)
at org.picocontainer.injectors.SingleMemberInjector.getParameter(SingleMemberInjector.java:78)
at org.picocontainer.injectors.ConstructorInjector$CtorAndAdapters.getParameterArguments(ConstructorInjector.java:309)
at org.picocontainer.injectors.ConstructorInjector$1.run(ConstructorInjector.java:335)
at org.picocontainer.injectors.AbstractInjector$ThreadLocalCyclicDependencyGuard.observe(AbstractInjector.java:270)
at org.picocontainer.injectors.ConstructorInjector.getComponentInstance(ConstructorInjector.java:364)
at org.picocontainer.injectors.AbstractInjectionFactory$LifecycleAdapter.getComponentInstance(AbstractInjectionFactory.java:56)
at org.picocontainer.behaviors.AbstractBehavior.getComponentInstance(AbstractBehavior.java:64)
at org.picocontainer.behaviors.Stored.getComponentInstance(Stored.java:91)
at org.picocontainer.DefaultPicoContainer.instantiateComponentAsIsStartable(DefaultPicoContainer.java:1034)
at org.picocontainer.DefaultPicoContainer.addAdapterIfStartable(DefaultPicoContainer.java:1026)
at org.picocontainer.DefaultPicoContainer.startAdapters(DefaultPicoContainer.java:1003)
at org.picocontainer.DefaultPicoContainer.start(DefaultPicoContainer.java:767)
at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:141)
at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:127)
at org.sonar.scanner.task.ScanTask.execute(ScanTask.java:47)
at org.sonar.scanner.task.TaskContainer.doAfterStart(TaskContainer.java:86)
at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:142)
at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:127)
at org.sonar.scanner.bootstrap.GlobalContainer.executeTask(GlobalContainer.java:115)
at org.sonar.batch.bootstrapper.Batch.executeTask(Batch.java:116)
at org.sonarsource.scanner.api.internal.batch.BatchIsolatedLauncher.execute(BatchIsolatedLauncher.java:62)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.sonarsource.scanner.api.internal.IsolatedLauncherProxy.invoke(IsolatedLauncherProxy.java:60)
at com.sun.proxy.$Proxy0.execute(Unknown Source)
at org.sonarsource.scanner.api.EmbeddedScanner.doExecute(EmbeddedScanner.java:233)
at org.sonarsource.scanner.api.EmbeddedScanner.runAnalysis(EmbeddedScanner.java:151)
at org.sonarsource.scanner.cli.Main.runAnalysis(Main.java:110)
at org.sonarsource.scanner.cli.Main.execute(Main.java:74)
at org.sonarsource.scanner.cli.Main.main(Main.java:61)
Caused by: java.lang.IllegalStateException: Unable to load component class org.sonar.scanner.rule.ModuleQProfiles
at org.sonar.core.platform.ComponentContainer$ExtendedDefaultPicoContainer.getComponent(ComponentContainer.java:69)
at org.picocontainer.DefaultPicoContainer.getComponent(DefaultPicoContainer.java:632)
at org.picocontainer.parameters.BasicComponentParameter$1.resolveInstance(BasicComponentParameter.java:118)
at org.picocontainer.parameters.ComponentParameter$1.resolveInstance(ComponentParameter.java:136)
at org.picocontainer.injectors.SingleMemberInjector.getParameter(SingleMemberInjector.java:78)
at org.picocontainer.injectors.ConstructorInjector$CtorAndAdapters.getParameterArguments(ConstructorInjector.java:309)
at org.picocontainer.injectors.ConstructorInjector$1.run(ConstructorInjector.java:335)
at org.picocontainer.injectors.AbstractInjector$ThreadLocalCyclicDependencyGuard.observe(AbstractInjector.java:270)
at org.picocontainer.injectors.ConstructorInjector.getComponentInstance(ConstructorInjector.java:364)
at org.picocontainer.injectors.AbstractInjectionFactory$LifecycleAdapter.getComponentInstance(AbstractInjectionFactory.java:56)
at org.picocontainer.behaviors.AbstractBehavior.getComponentInstance(AbstractBehavior.java:64)
at org.picocontainer.behaviors.Stored.getComponentInstance(Stored.java:91)
at org.picocontainer.DefaultPicoContainer.getInstance(DefaultPicoContainer.java:699)
at org.picocontainer.DefaultPicoContainer.getComponent(DefaultPicoContainer.java:647)
at org.sonar.core.platform.ComponentContainer$ExtendedDefaultPicoContainer.getComponent(ComponentContainer.java:67)
... 37 more
Caused by: org.sonarqube.ws.client.HttpException: Error 500 on url: {"errors":[{"msg":"An error has occurred. Please contact your administrator."}]}
at org.sonarqube.ws.client.BaseResponse.failIfNotSuccessful(BaseResponse.java:36)
at org.sonar.scanner.bootstrap.BatchWsClient.failIfUnauthorized(BatchWsClient.java:102)
at org.sonar.scanner.bootstrap.BatchWsClient.call(BatchWsClient.java:71)
at org.sonar.scanner.repository.DefaultQualityProfileLoader.loadResource(DefaultQualityProfileLoader.java:64)
at org.sonar.scanner.repository.DefaultQualityProfileLoader.load(DefaultQualityProfileLoader.java:59)
at org.sonar.scanner.repository.QualityProfileProvider.provide(QualityProfileProvider.java:46)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.picocontainer.injectors.MethodInjector.invokeMethod(MethodInjector.java:129)
at org.picocontainer.injectors.MethodInjector.access$000(MethodInjector.java:39)
at org.picocontainer.injectors.MethodInjector$2.run(MethodInjector.java:113)
at org.picocontainer.injectors.AbstractInjector$ThreadLocalCyclicDependencyGuard.observe(AbstractInjector.java:270)
at org.picocontainer.injectors.MethodInjector.decorateComponentInstance(MethodInjector.java:120)
at org.picocontainer.injectors.CompositeInjector.decorateComponentInstance(CompositeInjector.java:58)
at org.picocontainer.injectors.Reinjector.reinject(Reinjector.java:142)
at org.picocontainer.injectors.ProviderAdapter.getComponentInstance(ProviderAdapter.java:96)
at org.picocontainer.DefaultPicoContainer.getInstance(DefaultPicoContainer.java:699)
at org.picocontainer.DefaultPicoContainer.getComponent(DefaultPicoContainer.java:647)
at org.sonar.core.platform.ComponentContainer$ExtendedDefaultPicoContainer.getComponent(ComponentContainer.java:67)
... 51 more
ERROR:
ERROR: Re-run SonarQube Scanner using the -X switch to enable full debug logging.
System.Exception: Unexpected exit code received from batch file: 1
at Microsoft.TeamFoundation.DistributedTask.Task.Internal.PowerShell.InvokeBatchScriptCmdlet.ProcessRecord()
at System.Management.Automation.CommandProcessor.ProcessRecord()
```

**Comment by HughWood** [comment]
Access denied, you need to check your external access, credentials and authentication to sonarqube from vsts.

Kind regards,
Hugh Wood
Lead Developer
Rencore GmbH

**Comment by baywet** [comment]
Hey @HughWood I don't understand, the exact same build definition with exact same settings and SQ project work properly when the rencore plugins are not installed. Do these plugins have special authentication requirements?

**Comment by HughWood** [comment]
Then there is a part of the log missing, and an exception is being thrown. The most likely candidate would be the language definition plugins haven't been installed, or you have overlap with one of them and an existing plugin.

Check both log files in the log folder on your sonarqube installation.

Kind regards,
Hugh Wood
Lead Developer
Rencore GmbH

**Comment by baywet** [comment]
As per the readme I only installed sonar-scpaf-plugin sonar-spcaf-language-definition-ps1-plugin and sonar-spcaf-language-definition-aspx-plugin as I already have plugins for css, js and xml.
Am I missing something here?
Thanks for your help

**Comment by HughWood** [comment]
Your log files on your sonarqube installation will tell you if anything is wrong with the plugins.

Kind regards,
Hugh Wood
Lead Developer
Rencore GmbH

**Comment by baywet** [comment]
Thanks for your support during all that @HughWood  During the sprint planning today the team evaluated that setting up rencore/spcaf took way too much time and we'll move on. I'll close this one.

**Comment by matthiaseinig** [comment]
Hi Vincent,

We're sorry to hear that you had trouble configuring SPCAF with SonarQube. As discussed we would have been happy to assist your setup process in a remote session but we understand that you had to attend to more urgent matters at this time. We are going to investigate the setup process to see if there is anything that we can do, to improve it. In the meanwhile, please don't hesitate to reach out to us, if there is anything that we could assist you with.

Best Regards,
Matthias
